site_name: Meridian Information
# repo_url: https://github.com/example/repository/

docs_dir: source/docs

nav:
    - Home: 'index.md'
    - 'Quick Start':
        - 'Meridian TWIN': 'QuickStart/Meridian_TWIN.md'
        - 'Meridian LITE': 'QuickStart/Meridian_LITE.md'
        - 'Merimote': 'QuickStart/Merimote.md'
    - 'Protocol':
        - 'Meridim90':
            - 'index ': 'Protocol/Meridim90/overview90.md'
            - '[0] master command': 'Protocol/Meridim90/master_command.md'
            - '[1] sequential number': 'Protocol/Meridim90/sequential_number.md'
            - '[15-18] remort controller': 'Protocol/Meridim90/remort_controller.md'
            - '[88] error code': 'Protocol/Meridim90/error_code.md'
        - 'MeridimFX':
            - 'overview ': 'Protocol/MeridimFx/overviewFX.md'
    - 'Software':
        - 'Meridian console ': 'Software/Meridian_console.md'
        - 'Meridian unity ': 'Software/Meridian_unity.md'
    - 'Hardware':
        - 'Architecture ': 'Hardware/architecture.md'
        - 'Boards ': 'Hardware/boards.md'
    - 'URDF':
        - 'Roid1 ': 'URDF/Roid1.md'
    - 'Coding':
        - 'Guidelines': 'Coding/codingguidelines.md'
        - 'Valuable Index':
            - '#define basic': 'Coding/ValuableIndex/define_basic.md'
            - '#define servos': 'Coding/ValuableIndex/define_servos.md'
            - '#define meridim90': 'Coding/ValuableIndex/define_meridim90.md'
            - '#define master': 'Coding/ValuableIndex/define_master.md'
            - '#define error': 'Coding/ValuableIndex/define_error.md'
            - 'local value': 'Coding/ValuableIndex/local_val.md'
        - 'Library Function':
            - 'Index': 'Coding/Library/index.md'
            - 'cksm_rslt': 'Coding/Library/cksm_rslt.md'
            - 'cksm_val': 'Coding/Library/cksm_val.md'
            - 'seq_increase_num': 'Coding/Library/seq_increase_num.md'
            - 'seq_predict_num': 'Coding/Library/seq_predict_num.md'
            - 'seq_compare_nums': 'Coding/Library/seq_compare_nums.md'
            - 'HfShort2float': 'Coding/Library/HfShort2float.md'
            - 'float2HfShort': 'Coding/Library/float2HfShort.md'
            - 'Deg2Krs': 'Coding/Library/Deg2Krs.md'
            - 'HfDeg2Krs': 'Coding/Library/HfDeg2Krs.md'
            - 'Krs2Deg': 'Coding/Library/Krs2Deg.md'
            - 'Krs2HfDeg': 'Coding/Library/Krs2HfDeg.md'
            - 'Deg2RSxx': 'Coding/Library/Deg2RSxx.md'
            - 'HfDeg2RSxx': 'Coding/Library/HfDeg2RSxx.md'
            - 'RSxx2Deg': 'Coding/Library/RSxx2Deg.md'
            - 'RSxx2HfDeg': 'Coding/Library/RSxx2HfDeg.md'
            - 'print_tsy_hello': 'Coding/Library/print_tsy_hello.md'
            - 'print_esp_hello_start': 'Coding/Library/print_esp_hello_start.md'
            - 'print_esp_hello_ip': 'Coding/Library/print_esp_hello_ip.md'
            - 'print_imuahrs': 'Coding/Library/print_imuahrs.md'
            - 'print_servo_mounts': 'Coding/Library/print_servo_mounts.md'
            - 'print_controlpad': 'Coding/Library/print_controlpad.md'
            - 'monitor_check_flow': 'Coding/Library/monitor_check_flow.md'
            - 'monitor_joypad': 'Coding/Library/monitor_joypad.md'
            - 'monitor_servo_error': 'Coding/Library/monitor_servo_error.md'
        - 'Local Function':
            - 'execute_master_command_1' : 'Coding/LocalFunction/execute_master_command_1.md'
            - 'execute_master_command_2' : 'Coding/LocalFunction/execute_master_command_2.md'
            - 'mrd_udp_receive' : 'Coding/LocalFunction/mrd_udp_receive.md'
            - 'mrd_udp_send' : 'Coding/LocalFunction/mrd_udp_send.md'
            - 'mrd_eeprom_init' : 'Coding/LocalFunction/mrd_eeprom_init.md'
            - 'mrd_eeprom_read' : 'Coding/LocalFunction/mrd_eeprom_read.md'
            - 'mrd_eeprom_write_read_check' : 'Coding/LocalFunction/mrd_eeprom_write_read_check.md'
            - 'mrd_eeprom_make_data_from_config' : 'Coding/LocalFunction/mrd_eeprom_make_data_from_config.md'
            - 'mrd_eeprom_dump_at_boot' : 'Coding/LocalFunction/mrd_eeprom_dump_at_boot.md'
            - 'mrd_eeprom_dump_to_serial' : 'Coding/LocalFunction/mrd_eeprom_dump_to_serial.md'
            - 'mrd_wire0_init_i2c' : 'Coding/LocalFunction/mrd_wire0_init_i2c.md'
            - 'mrd_wire0_init_mpu6050_dmp' : 'Coding/LocalFunction/mrd_wire0_init_mpu6050_dmp.md'
            - 'mrd_wire0_init_bno055' : 'Coding/LocalFunction/mrd_wire0_init_bno055.md'
            - 'mrd_wire0_run' : 'Coding/LocalFunction/mrd_wire0_run.md'
            - 'mrd_wire0_startIntervalTimer' : 'Coding/LocalFunction/mrd_wire0_startIntervalTimer.md'
            - 'mrd_disp' : 'Coding/LocalFunction/mrd_disp.md'
            - 'mrd_servos_drive_lite' : 'Coding/LocalFunction/mrd_servos_drive_lite.md'
            - 'mrd_servos_all_off' : 'Coding/LocalFunction/mrd_servos_all_off.md'
            - 'mrd_move_init' : 'Coding/LocalFunction/mrd_move_init.md'
    - 'Tools':
        - 'MADIwrite RS30xTTL': 'Tools/MADIwrite.md'
    - 'Misc':
        - 'Joint and Link': 'Misc/joint_and_link.md'
    - 'Repositories':
        - 'Repositories': 'Misc/Repositories.md'
    - 'Philosophy': 
        - 'Design Philosophy': 'Philosophy/DesignPhilosophy.md'
    - 'Contributors': 
        - 'Contributors': 'https://note.com/ninagawa123/n/nbc8ec25bad69'






    - Blog: "https://note.com/ninagawa123/n/nb768563591be"

theme: windmill

markdown_extensions:
    - toc:
        permalink: True

plugins:
