site_name: Meridian Information
# repo_url: https://github.com/example/repository/

docs_dir: source/docs

nav:
    - Home: 'index.md'
    - 'Quick Start':
        - 'Meridian TWIN': 'QuickStart/Meridian_TWIN.md'
        - 'Meridian LITE': 'QuickStart/Meridian_LITE.md'
    - 'about Meridim':
        - 'overview ': 'aboutMeridim/overview.md'
        - '[0] master command': 'aboutMeridim/master_command.md'
        - '[1] sequential number': 'aboutMeridim/sequential_number.md'
        - '[15-18] remort controller': 'aboutMeridim/remort_controller.md'
        - '[88] error code': 'aboutMeridim/error_code.md'
    - 'Valuable Index':
        - '#define basic': 'ValuableIndex/define_basic.md'
        - '#define servos': 'ValuableIndex/define_servos.md'
        - '#define meridim90': 'ValuableIndex/define_meridim90.md'
        - '#define master': 'ValuableIndex/define_master.md'
        - 'local value': 'ValuableIndex/local_val.md'
    - 'Library Function':
        - 'Index': 'Library/index.md'
        - 'cksm_rslt': 'Library/cksm_rslt.md'
        - 'cksm_val': 'Library/cksm_val.md'
        - 'seq_increase_num': 'Library/seq_increase_num.md'
        - 'seq_predict_num': 'Library/seq_predict_num.md'
        - 'seq_compare_nums': 'Library/seq_compare_nums.md'
        - 'HfShort2float': 'Library/HfShort2float.md'
        - 'float2HfShort': 'Library/float2HfShort.md'
        - 'Deg2Krs': 'Library/Deg2Krs.md'
        - 'HfDeg2Krs': 'Library/HfDeg2Krs.md'
        - 'Krs2Deg': 'Library/Krs2Deg.md'
        - 'Krs2HfDeg': 'Library/Krs2HfDeg.md'
        - 'Deg2RSxx': 'Library/Deg2RSxx.md'
        - 'HfDeg2RSxx': 'Library/HfDeg2RSxx.md'
        - 'RSxx2Deg': 'Library/RSxx2Deg.md'
        - 'RSxx2HfDeg': 'Library/RSxx2HfDeg.md'
        - 'print_tsy_hello': 'Library/print_tsy_hello.md'
        - 'print_esp_hello_start': 'Library/print_esp_hello_start.md'
        - 'print_esp_hello_ip': 'Library/print_esp_hello_ip.md'
        - 'print_imuahrs': 'Library/print_imuahrs.md'
        - 'print_servo_mounts': 'Library/print_servo_mounts.md'
        - 'print_controlpad': 'Library/print_controlpad.md'
        - 'monitor_check_flow': 'Library/monitor_check_flow.md'
        - 'monitor_joypad': 'Library/monitor_joypad.md'
        - 'monitor_servo_error': 'Library/monitor_servo_error.md'
    - 'Misc':
        - 'Joint and Link': 'Misc/joint_and_link.md'

    - Blog: "https://note.com/ninagawa123/n/nb768563591be"

theme: windmill

markdown_extensions:
    - toc:
        permalink: True

plugins:
